spring:
  application:
    name: totalexam
  
  # H2 데이터베이스 설정
  datasource:
    url: jdbc:h2:mem:totalexam;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  # H2 Console 활성화
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true
  
  # SQL 초기화 설정
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

# JWT 토큰 설정
jwt:
  secret: totalexam-secret-key-for-jwt-token-generation-and-validation-very-long-key
  expiration: 86400000  # 24시간 (밀리초)

# 로깅 설정
logging:
  level:
    root: INFO
    com.example.totalexam: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always

# 서버 포트 설정
server:
  port: 8082 