# application-local.yml - 로컬 환경 전용 설정 (5.4절 예제)

server:
  port: 8080

logging:
  level:
    root: debug
    com.example.configdemo: debug
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# 로컬 개발용 데이터베이스 설정
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver

# 로컬 환경 특화 설정
app:
  environment: "local"
  debug-mode: true
  cache-enabled: false
  features:
    mock-external-api: true
    log-all-requests: true 