# 개발 환경 설정
server:
  port: 8081

app:
  name: Spring Profile Demo (개발환경)
  environment: development
  description: 개발 환경에서 실행되는 Spring Boot 애플리케이션
  version: 1.0.0-DEV
  database:
    url: jdbc:mysql://localhost:3306/dev_db
    username: dev_user
    password: dev_password
    max-connections: 10
  features:
    debug-mode: true
    enable-cache: false
    enable-metrics: true
    timeout: 5000

# 개발 환경 로깅 설정
logging:
  level:
    root: DEBUG
    com.example.springprofiledemo: DEBUG
    org.springframework.web: DEBUG

# 개발 환경에서만 사용하는 설정
management:
  endpoints:
    web:
      exposure:
        include: "*"  # 모든 actuator endpoint 노출 