spring:
  application:
    name: datajdbc
    
  # H2 임베딩 데이터베이스 설정
  datasource:
    url: jdbc:h2:mem:testdb;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    
  # H2 Console 설정 (개발용)
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
        
  # SQL 로깅 설정
  sql:
    init:
      mode: always
      
# 서버 포트 설정
server:
  port: 8080
  
# 로깅 설정
logging:
  level:
    com.example.datajdbc: DEBUG
    org.springframework.jdbc: DEBUG
    org.springframework.data.jdbc: DEBUG
    sql: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    
# 관리 엔드포인트 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always 