server:
  port: 8080

spring:
  application:
    name: beanexam

# Actuator 설정 - Bean 정보 확인을 위해
management:
  endpoints:
    web:
      exposure:
        include: beans, health, info, env
  endpoint:
    beans:
      enabled: true

# 커스텀 설정 - Configuration Properties 예시용
app:
  name: "Bean Example Application"
  version: "1.0.0"
  description: "Spring Bean 개념 학습을 위한 예제 애플리케이션"
  database:
    url: "jdbc:h2:mem:testdb"
    username: "sa"
    password: ""

logging:
  level:
    com.example.beanexam: DEBUG
    org.springframework.web: INFO 